spring.application.name=expensia-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/expensia}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Khaled@2004}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

ai.base-url=${AI_BASE_URL:http://localhost:8000/api}